apiVersion: v1
kind: Template
metadata:
  name: osb-starter-pack
objects:

- apiVersion: servicecatalog.k8s.io/v1beta1
  kind: ClusterServiceBroker
  metadata:
    name: osb-starter-pack
  spec:
    url: http://osb-starter-pack.osb-starter-pack.svc.cluster.local

- kind: ServiceAccount
  apiVersion: v1
  metadata:
    name: osb-starter-pack

- kind: Service
  apiVersion: v1
  metadata:
    name: osb-starter-pack
    labels:
      app: osb-starter-pack
  spec:
    selector:
      app: osb-starter-pack
    ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
- kind: Deployment
  apiVersion: extensions/v1beta1
  metadata:
    name: osb-starter-pack
    labels:
      app: osb-starter-pack
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: osb-starter-pack
    template:
      metadata:
        labels:
          app: osb-starter-pack
      spec:
        containers:
        - name: service-osb-starter-pack
          image: ${IMAGE}
          imagePullPolicy: IfNotPresent
          command:
          - /opt/servicebroker/servicebroker
          args:
          - --port
          - "8080"
          - -v
          - "4"
          - --logtostderr
          ports:
          - containerPort: 8080
          readinessProbe:
            tcpSocket:
              port: 8080
            failureThreshold: 1
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2
          livenessProbe:
            tcpSocket:
              port: 8080
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 2

parameters:
- description: Name of the image to use
  displayName: Image name
  name: IMAGE
  required: true
  value: quay.io/osb-starter-pack/servicebroker:latest
